clc;
load spambase.data;
spambase = spambase(randperm(size(spambase,1)),:);
fid = fopen('spamdata.txt','w');
x = repmat('%5.4f\t',1,57);
fprintf(fid,[x,'%d\n'],spambase');
fclose(fid) ;
%x_1=fopen('spamdata.txt');
A=importdata('spamdata.txt');
disp(size(A));
